 module.exports = {
		devs:"784942624522895360",
    messageid:"",
    channelid:"",
    wantedid:"",
    authorid:"",
     rolesAuthorid:"",
    prefix: "+",
    prefixayar:"kapalı",
    kurallar: "off",
    durum: "Bakımdayım.",
  afketiket:"off",
  afketiketsayı:"0",
  afk:"no",
  afksüre:"",
  afkmsg:"",
  linkengel:"",
  bakımmodu:"",
  bakımsüre:"00",
  bakım:"off",
  kl:"off",
  loop:"",
  liste: "",
  müzikid: "",
  şarkı: "off",
  kurallar:"yok",
  müzikkanal:"",
  channelid:"?",
  aktifliksure:"00",
  kl:"yok",
  klsebep:"",
  klsüre:"00",
  klekleyen:"",
  xp:"0",
    nextlevelxp:"100",
    level:"0",
  mesajsayısı:"0",
    xphız:"2",
    xplog:"off",
    ranksistem: "kapalı",
    ranka: "off",
    kurallar:"off",
    ktoplam:"0",
  bakım:"off",
  bakımmodu:"",
  bakımsure:"00",
  bakımek:"",
  Bilet_Kategori:"",
  capsengel:"kapalı",
  linkengel:"kapalı",
  otorol:"",
  otorolk:"",
  ototag:"",
  ototagsistem:"kapalı",
  otoisim:"",
  otoisimsistem:"kapalı",
  capsengelayar:":hayir:",
  seviyeayar:":hayir:",
  otoisimayar:":hayir:",
  ototagayar:":hayir:",
  otorolayar:":hayir:",
  linkengelayar:":hayir:",
  botrolayar:":hayir:",
  otorolkanal:"",
  otorolrol:"",
  otorolsistem:"kapalı",
  botrol:"",
  botrolsistem:"kapalı",
  botrolkanal:"",
  dc:"",
  dc1:"",
  sayı:"kapalı",
  isimş:"",
  hgbbsistem:"",
  hgbbkanal:"",
  komut:"En son eklenen komut verisi bulunmuyor.", 
  para:"0",
  durum2:"7/24 Aktif!",
  durum3:"Kullanıcılarını",
  kullanıcı:"",
  menü:"Yok",
  buton:"Yok",
  soru:"Yok",
  butonRolIDs:"",
  butonRolEmojis:"",
  butonRolMesaj: "",
  botlog:"",
  botlistacik:"Kapalı",
  botlistgeliştirici:"",
  botlistbot:"",
  botlistbotid:"",
  botlistyetkili:"",
  botlistyetkiliaçık:"Kapalı",
  botlistgeliştiriciaçık:"Kapalı",
  botlistbotidacik:"",
    botlistbotk:"",
    botlistsahip:"",
    botlistbotsahip:"",
    botlistsahiplik: "",
    botlistkanal: "1170675876300587041",
    botlistbotsahiprol: "1200073647830880348",
    botlistbotrol: "1200073616923045979",
    botID: "",
    botprefix: "",
    botlist: "kapalı",
    ownerID: "",
    ownerID2: "",
    botmesajıd: "",
    yid:"",
    sonrakikişi: "",
    sonrakisayı: "",
    sayısaymacasistem: "kapalı",
    sayıkanal: "",
    sonrakikullanıcı: "",

}